In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
df = pd.read_csv('customer_data.csv')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Customer ID      250000 non-null  int64
 1   Customer Name    250000 non-null  object
 2   Age              250000 non-null  int64
 3   Gender           250000 non-null  object
 4   Location         0 non-null       float64
 5   MembershipLevel  0 non-null       float64
 6   Churn            250000 non-null  int64
dtypes: float64(2), int64(3), object(2)
memory usage: 13.4+ MB

In [16]:
df.head(10)

   Customer ID   Customer Name  Age  Gender  Location  MembershipLevel  Churn
0        44605     John Rivera   31  Female       NaN              NaN      0
1        44605     John Rivera   31  Female       NaN              NaN      0
2        44605     John Rivera   31  Female       NaN              NaN      0
3        44605     John Rivera   31  Female       NaN              NaN      0
4        44605     John Rivera   31  Female       NaN              NaN      0
5        13738  Lauren Johnson   27  Female       NaN              NaN      0
6        13738  Lauren Johnson   27  Female       NaN              NaN      0
7        13738  Lauren Johnson   27  Female       NaN              NaN      0
8        13738  Lauren Johnson   27  Female       NaN              NaN      0
9        13738  Lauren Johnson   27  Female       NaN              NaN      0

In [17]:
unique_customer_ids = df['Customer ID'].unique()
# Shuffle the unique customer IDs randomly
np.random.shuffle(unique_customer_ids)

# Create a mapping dictionary for membershiplevel and location
membershiplevel_mapping = {cust_id: np.random.choice(['Bronze', 'Silver', 'Gold', 'Platinum']) for cust_id in unique_customer_ids}
location_mapping = {cust_id: np.random.choice(['United States', 'Canada']) for cust_id in unique_customer_ids}

# Assign values to 'membershiplevel' and 'location' based on the mappings
df['MembershipLevel'] = df['Customer ID'].map(membershiplevel_mapping)
df['Location'] = df['Customer ID'].map(location_mapping)

df.head(20)

,Customer ID,Customer Name,Age,Gender,Location,MembershipLevel,Churn
0,44605,John Rivera,31,Female,United States,Platinum,0
1,44605,John Rivera,31,Female,United States,Platinum,0
2,44605,John Rivera,31,Female,United States,Platinum,0
3,44605,John Rivera,31,Female,United States,Platinum,0
4,44605,John Rivera,31,Female,United States,Platinum,0
5,13738,Lauren Johnson,27,Female,United States,Silver,0
6,13738,Lauren Johnson,27,Female,United States,Silver,0
7,13738,Lauren Johnson,27,Female,United States,Silver,0
8,13738,Lauren Johnson,27,Female,United States,Silver,0
9,13738,Lauren Johnson,27,Female,United States,Silver,0
10,33969,Carol Allen,27,Male,Canada,Silver,0
11,33969,Carol Allen,27,Male,Canada,Silver,0
12,33969,Carol Allen,27,Male,Canada,Silver,0
13,33969,Carol Allen,27,Male,Canada,Silver,0
14,33969,Carol Allen,27,Male,Canada,Silver,0
15,33969,Carol Allen,27,Male,Canada,Silver,0
16,33969,Carol Allen,27,Male,Canada,Silver,0
17,42650,Curtis Smith,20,Female,United States,Silver,0
18,42650,Curtis Smith,20,Female,United States,Silver,0
19,42650,Curtis Smith,20,Female,United States,Silver,0

In [18]:
# Set the percentage of values to change for each category
percentage_male_change = 20
percentage_female_change = 30
percentage_us_change = 30
percentage_ca_change = 20

# Change 'gender' column
male_indices_to_change = df[df['Gender'] == 'Male'].sample(frac=percentage_male_change/100).index
df.loc[male_indices_to_change, 'Gender'] = np.random.choice(['m', 'male', 'M'], size=len(male_indices_to_change))
female_indices_to_change = df[df['Gender'] == 'Female'].sample(frac=percentage_female_change/100).index
df.loc[female_indices_to_change, 'Gender'] = np.random.choice(['f', 'female', 'F'], size=len(female_indices_to_change))

# Change 'location' column
us_indices_to_change = df[df['Location'] == 'United States'].sample(frac=percentage_us_change/100).index
df.loc[us_indices_to_change, 'Location'] = 'US'

ca_indices_to_change = df[df['Location'] == 'Canada'].sample(frac=percentage_ca_change/100).index
df.loc[ca_indices_to_change, 'Location'] = 'CA'

df.head(10)

,Customer ID,Customer Name,Age,Gender,Location,MembershipLevel,Churn
0,44605,John Rivera,31,f,United States,Platinum,0
1,44605,John Rivera,31,Female,US,Platinum,0
2,44605,John Rivera,31,Female,US,Platinum,0
3,44605,John Rivera,31,Female,United States,Platinum,0
4,44605,John Rivera,31,Female,US,Platinum,0
5,13738,Lauren Johnson,27,Female,US,Silver,0
6,13738,Lauren Johnson,27,f,United States,Silver,0
7,13738,Lauren Johnson,27,Female,United States,Silver,0
8,13738,Lauren Johnson,27,female,US,Silver,0
9,13738,Lauren Johnson,27,Female,United States,Silver,0

In [19]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/gdrive')

# Assuming 'df' is your DataFrame
df.to_csv('/content/gdrive/My Drive/customer_data.csv', index=False)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [20]:
df2 = pd.read_csv('sales_data.csv')

In [21]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CustomerID                250000 non-null  int64
 1   LastPurchaseDate          250000 non-null  object
 2   PurchasedProductCategory  250000 non-null  object
 3   ProductPrice              250000 non-null  int64
 4   TotalPurchases            250000 non-null  int64
 5   TotalSpent                250000 non-null  int64
 6   PaymentMethod             250000 non-null  object
 7   Returns                   202618 non-null  float64
dtypes: float64(1), int64(4), object(3)
memory usage: 15.3+ MB

In [22]:
df2.head(10)

,CustomerID,LastPurchaseDate,PurchasedProductCategory,ProductPrice,TotalPurchases,TotalSpent,PaymentMethod,Returns
0,44605,3/5/2023 21:30,Home,177,1,2427,PayPal,1.0
1,44605,16/5/2021 13:57,Electronics,174,3,2448,PayPal,1.0
2,44605,13/7/2020 6:16,Books,413,1,2345,Credit Card,1.0
3,44605,17/1/2023 13:14,Electronics,396,3,937,Cash,0.0
4,44605,1/5/2021 11:29,Books,259,4,2598,PayPal,1.0
5,13738,25/8/2022 6:48,Home,191,3,3722,Credit Card,1.0
6,13738,25/7/2023 5:17,Electronics,205,1,2773,Credit Card,NaN
7,13738,5/2/2023 19:31,Books,370,5,1486,Cash,1.0
8,13738,21/12/2021 3:29,Home,12,2,2175,Cash,NaN
9,13738,9/2/2023 0:53,Electronics,40,4,4327,Cash,0.0

In [23]:
# Assuming 'df' is your DataFrame with 'lastpurchasedate' column
df2['LastPurchaseDate'] = pd.to_datetime(df2['LastPurchaseDate']).dt.date

df2.head(10)

,CustomerID,LastPurchaseDate,PurchasedProductCategory,ProductPrice,TotalPurchases,TotalSpent,PaymentMethod,Returns
0,44605,2023-03-05,Home,177,1,2427,PayPal,1.0
1,44605,2021-05-16,Electronics,174,3,2448,PayPal,1.0
2,44605,2020-07-13,Books,413,1,2345,Credit Card,1.0
3,44605,2023-01-17,Electronics,396,3,937,Cash,0.0
4,44605,2021-01-05,Books,259,4,2598,PayPal,1.0
5,13738,2022-08-25,Home,191,3,3722,Credit Card,1.0
6,13738,2023-07-25,Electronics,205,1,2773,Credit Card,NaN
7,13738,2023-05-02,Books,370,5,1486,Cash,1.0
8,13738,2021-12-21,Home,12,2,2175,Cash,NaN
9,13738,2023-09-02,Electronics,40,4,4327,Cash,0.0

In [24]:
# Assuming 'df' is your DataFrame
df2.to_csv('/content/gdrive/My Drive/sales_data.csv', index=False)

In [25]:
df3 = pd.read_csv('integrated_ecom.csv')

In [26]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 14 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CustomerID                250000 non-null  int64
 1   LastPurchaseDate          250000 non-null  object
 2   PurchasedProductCategory  250000 non-null  object
 3   ProductPrice              250000 non-null  int64
 4   TotalPurchases            250000 non-null  int64
 5   TotalSpent                250000 non-null  int64
 6   PaymentMethod             250000 non-null  object
 7   Returns                   202618 non-null  float64
 8   CustomerName              250000 non-null  object
 9   Age                       250000 non-null  int64
 10  Gender                    250000 non-null  object
 11  Location                  250000 non-null  object
 12  MembershipLevel           250000 non-null  object
 13  Churn                     250000 non-null  int64
dtypes: float64(1), int64(6), object(7)
memory usage: 26.7+ MB

In [27]:
df3.head(10)

,CustomerID,LastPurchaseDate,PurchasedProductCategory,ProductPrice,TotalPurchases,TotalSpent,PaymentMethod,Returns,CustomerName,Age,Gender,Location,MembershipLevel,Churn
0,44605,5/3/2023,Home,177,1,2427,PayPal,1.0,John Rivera,31,f,United States,Platinum,0
1,44605,16/5/2021,Electronics,174,3,2448,PayPal,1.0,John Rivera,31,Female,US,Platinum,0
2,44605,13/7/2020,Books,413,1,2345,Credit Card,1.0,John Rivera,31,Female,US,Platinum,0
3,44605,17/1/2023,Electronics,396,3,937,Cash,0.0,John Rivera,31,Female,United States,Platinum,0
4,44605,5/1/2021,Books,259,4,2598,PayPal,1.0,John Rivera,31,Female,US,Platinum,0
5,13738,25/8/2022,Home,191,3,3722,Credit Card,1.0,Lauren Johnson,27,Female,US,Silver,0
6,13738,25/7/2023,Electronics,205,1,2773,Credit Card,NaN,Lauren Johnson,27,f,United States,Silver,0
7,13738,2/5/2023,Books,370,5,1486,Cash,1.0,Lauren Johnson,27,Female,United States,Silver,0
8,13738,21/12/2021,Home,12,2,2175,Cash,NaN,Lauren Johnson,27,female,US,Silver,0
9,13738,2/9/2023,Electronics,40,4,4327,Cash,0.0,Lauren Johnson,27,Female,United States,Silver,0

In [28]:
# Assuming 'df' is your DataFrame with 'gender' and 'location' columns
mapping_gender = {'m': 'Male', 'male': 'Male', 'M': 'Male', 'f': 'Female', 'female': 'Female', 'F': 'Female'}
mapping_location = {'US': 'United States', 'CA': 'Canada'}

# Replace values in 'gender' and 'location' columns
df3['Gender'] = df3['Gender'].replace(mapping_gender)
df3['Location'] = df3['Location'].replace(mapping_location)

df3.head(10)

,CustomerID,LastPurchaseDate,PurchasedProductCategory,ProductPrice,TotalPurchases,TotalSpent,PaymentMethod,Returns,CustomerName,Age,Gender,Location,MembershipLevel,Churn
0,44605,5/3/2023,Home,177,1,2427,PayPal,1.0,John Rivera,31,Female,United States,Platinum,0
1,44605,16/5/2021,Electronics,174,3,2448,PayPal,1.0,John Rivera,31,Female,United States,Platinum,0
2,44605,13/7/2020,Books,413,1,2345,Credit Card,1.0,John Rivera,31,Female,United States,Platinum,0
3,44605,17/1/2023,Electronics,396,3,937,Cash,0.0,John Rivera,31,Female,United States,Platinum,0
4,44605,5/1/2021,Books,259,4,2598,PayPal,1.0,John Rivera,31,Female,United States,Platinum,0
5,13738,25/8/2022,Home,191,3,3722,Credit Card,1.0,Lauren Johnson,27,Female,United States,Silver,0
6,13738,25/7/2023,Electronics,205,1,2773,Credit Card,NaN,Lauren Johnson,27,Female,United States,Silver,0
7,13738,2/5/2023,Books,370,5,1486,Cash,1.0,Lauren Johnson,27,Female,United States,Silver,0
8,13738,21/12/2021,Home,12,2,2175,Cash,NaN,Lauren Johnson,27,Female,United States,Silver,0
9,13738,2/9/2023,Electronics,40,4,4327,Cash,0.0,Lauren Johnson,27,Female,United States,Silver,0

In [29]:
# Assuming 'df' is your DataFrame
missing_columns = df3.columns[df3.isnull().any()]

print("Columns with missing values:")
print(missing_columns)

Columns with missing values:
Index(['Returns'], dtype='object')

In [30]:
# Assuming 'df' is your DataFrame
df3.to_csv('/content/gdrive/My Drive/integrated_ecom.csv', index=False)